export const IMAGES = {
  heroBg: require("./images/hero_bg.png"),
  heroFamily: require("./images/hero_family.png"),
  nurse: require("./images/nurse.png"),
  caregiving: require("./images/caregiving.png"),
  mask: require("./images/mask.png"),
  medical: require("./images/medical.png"),
  bookingImg1: require("./images/booking_image1.png"),
  bookingImg2: require("./images/booking_image2.png"),
  bookingImg3: require("./images/booking_image3.png"),
  iPhoneLogo: require("./images/ip_with_logo.png"),
  jagasImg1: require("./images/jagas_img1.png"),
  jagasImg2: require("./images/jagas_img2.png"),
  jagasImg3: require("./images/jagas_img3.png"),
  partner_hca: require("./images/partner_hca.png"),
  partner_singcancer: require("./images/partner_singcancer.png"),
  partner_singhealth: require("./images/partner_singhealth.png"),
  partner_touch: require("./images/partner_touch.png"),
  partner_awwa: require("./images/partner_awwa.png"),
  partner_aic: require("./images/partner_aic.png"),
  partner_stlukes: require("./images/partner_stlukes.png"),
  partner_tantock: require("./images/partner_tantock.png"),
  partner_singhealth2: require("./images/partner_singhealth2.png"),
  award_eldercare: require("./images/award_eldercare.png"),
  award_gcic: require("./images/award_gcic.png"),
  award_president: require("./images/award_president.png"),
  award_income: require("./images/award_income.png"),
  award_singtel: require("./images/award_singtel.png"),
};

export const SVGS = {
  logo: require("./svgs/logo.svg"),
  chervonDown: require("./svgs/chervon-down.svg"),
  calendarTime: require("./svgs/calendar-time.svg"),
  userAdd: require("./svgs/user-add.svg"),
  userCall: require("./svgs/user-call.svg"),
  heart: require("./svgs/heart.svg"),
  handChecked: require("./svgs/checked-hand.svg"),
  cellphone: require("./svgs/cellphone.svg"),
  competent: require("./svgs/competent.svg"),
  trained: require("./svgs/trained.svg"),
  licensed: require("./svgs/licensed.svg"),
  personalInterview: require("./svgs/personal-interview.svg"),
  experience: require("./svgs/experience.svg"),
  jagas_bg1: require("./svgs/jagas_bg1.svg"),
  jagas_bg2: require("./svgs/jagas_bg2.svg"),
  phone: require("./svgs/phone.svg"),
  mail: require("./svgs/mail.svg"),
  house: require("./svgs/house.svg"),
  clock: require("./svgs/clock.svg"),
  social_media: require("./svgs/social_mdeia.svg"),
  quote: require("./svgs/quote.svg"),
  stars: require("./svgs/stars.svg"),
};
